# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('event', models.IntegerField(blank=True, help_text=b'An action performed in the room, either by a user or by the system (e.g. XYZ leaves room.', null=True, choices=[(1, b"has changed the room's description."), (2, b'has joined the room.'), (3, b'has left the room.')])),
                ('text', models.TextField(help_text=b'A message, either typed in by a user or generated by the system.', null=True, blank=True)),
                ('unix_timestamp', models.FloatField(help_text=b'Unix timestamp when this message was inserted into the database.', editable=False)),
                ('created', models.DateTimeField(editable=False)),
            ],
            options={
                'ordering': ['unix_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(help_text=b'Name of the room.', max_length=255, null=True, blank=True)),
                ('created', models.DateTimeField(editable=False)),
                ('description', models.CharField(help_text=b'The description of this room.', max_length=100, null=True, blank=True)),
                ('description_modified', models.IntegerField(help_text=b'Unix timestamp when the description was created or last modified.', null=True, editable=False)),
                ('last_activity', models.IntegerField(help_text=b'Last activity in the room. Stored as a Unix timestamp.', editable=False)),
                ('object_id', models.PositiveIntegerField(null=True, blank=True)),
                ('content_type', models.ForeignKey(blank=True, to='contenttypes.ContentType', null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(help_text=b'This message was posted in a given chat room.', to='jqchat.Room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(related_name='jchat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
